/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'verifying' : IDL.Null,
  'failed' : IDL.Null,
  'authorizing' : IDL.Null,
  'disbursing' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'totalChargedCents' : IDL.Nat,
  'status' : TransactionStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'errorMessage' : IDL.Opt(IDL.Text),
  'recipientEcocash' : IDL.Text,
  'amountCents' : IDL.Nat,
  'feeCents' : IDL.Nat,
  'senderName' : IDL.Text,
  'cardLast4' : IDL.Text,
  'contipayRef' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const ContiPayConfig = IDL.Record({
  'disburseEndpoint' : IDL.Text,
  'acquireEndpoint' : IDL.Text,
  'merchantId' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiSecret' : IDL.Text,
  'sslPemContent' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateFees' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'fee' : IDL.Nat,
          'totalCharged' : IDL.Nat,
          'netToRecipient' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'contipayAcquire' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          'errorMessage' : IDL.Text,
          'errorCode' : IDL.Text,
          'success' : IDL.Bool,
          'contipayRef' : IDL.Text,
        }),
      ],
      [],
    ),
  'contipayDisburse' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          'errorMessage' : IDL.Text,
          'errorCode' : IDL.Text,
          'success' : IDL.Bool,
          'contipayRef' : IDL.Text,
        }),
      ],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfig' : IDL.Func([], [ContiPayConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTransactionStatus' : IDL.Func(
      [IDL.Text, TransactionStatus, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'verifyWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'verifying' : IDL.Null,
    'failed' : IDL.Null,
    'authorizing' : IDL.Null,
    'disbursing' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'totalChargedCents' : IDL.Nat,
    'status' : TransactionStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'errorMessage' : IDL.Opt(IDL.Text),
    'recipientEcocash' : IDL.Text,
    'amountCents' : IDL.Nat,
    'feeCents' : IDL.Nat,
    'senderName' : IDL.Text,
    'cardLast4' : IDL.Text,
    'contipayRef' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const ContiPayConfig = IDL.Record({
    'disburseEndpoint' : IDL.Text,
    'acquireEndpoint' : IDL.Text,
    'merchantId' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiSecret' : IDL.Text,
    'sslPemContent' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateFees' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'fee' : IDL.Nat,
            'totalCharged' : IDL.Nat,
            'netToRecipient' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'contipayAcquire' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'errorMessage' : IDL.Text,
            'errorCode' : IDL.Text,
            'success' : IDL.Bool,
            'contipayRef' : IDL.Text,
          }),
        ],
        [],
      ),
    'contipayDisburse' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'errorMessage' : IDL.Text,
            'errorCode' : IDL.Text,
            'success' : IDL.Bool,
            'contipayRef' : IDL.Text,
          }),
        ],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfig' : IDL.Func([], [ContiPayConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTransactionStatus' : IDL.Func(
        [IDL.Text, TransactionStatus, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'verifyWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };