/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContiPayConfig {
  'disburseEndpoint' : string,
  'acquireEndpoint' : string,
  'merchantId' : string,
  'apiKey' : string,
  'apiSecret' : string,
  'sslPemContent' : string,
}
export interface Transaction {
  'id' : string,
  'totalChargedCents' : bigint,
  'status' : TransactionStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'errorMessage' : [] | [string],
  'recipientEcocash' : string,
  'amountCents' : bigint,
  'feeCents' : bigint,
  'senderName' : string,
  'cardLast4' : string,
  'contipayRef' : string,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'verifying' : null } |
  { 'failed' : null } |
  { 'authorizing' : null } |
  { 'disbursing' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'phoneNumber' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateFees' : ActorMethod<
    [bigint],
    { 'fee' : bigint, 'totalCharged' : bigint, 'netToRecipient' : bigint }
  >,
  'contipayAcquire' : ActorMethod<
    [string, bigint],
    {
      'errorMessage' : string,
      'errorCode' : string,
      'success' : boolean,
      'contipayRef' : string,
    }
  >,
  'contipayDisburse' : ActorMethod<
    [string, bigint],
    {
      'errorMessage' : string,
      'errorCode' : string,
      'success' : boolean,
      'contipayRef' : string,
    }
  >,
  'createTransaction' : ActorMethod<[bigint, string, string, string], string>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfig' : ActorMethod<[], ContiPayConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setConfig' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTransactionStatus' : ActorMethod<
    [string, TransactionStatus, string, [] | [string]],
    undefined
  >,
  'verifyWebhook' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];